### ISSUE TITLE
NFS support is mentioned but no "nfs subfolder" in plutoscripts

### ISSUE THREAD

**Issue by zanco** [LamaBleu/plutoscripts#2]
Hi.
the readme says:
- Added NFS filesystem support (under NFS subfolder).  
  You can now mount remote shares using NFS through USB or Wifi, save records and scripts.  

I cannot find the NFS subfolder in the plutoscripts ?

Mounting from the Pluto ends with error message mounting failed, no such device, the same command from a raspberry Pi does mount the network drive to the given folder

Any ideas ?

**Comment by LamaBleu** [comment]
Hi zanco,

The readme.txt on the github is just an overview.
Please have a look to the detailed NFS-readme.txt on my [mega drive](https://mega.nz/#F!C8hgFASK!C9DfCjU7ou46mG-LNWQTrQ!rxoQEY5J), describing step by step how to set-up your NFS environment (both pluto and computer sides). 

There is no NFS subfolder, you have to create your own on the remote computer, then set it in the config.txt.

Please report if any issue, providing details ;)

**Comment by LamaBleu** [comment]
Assuming it's solved, do not hesitate to re-open this issue if you need
